package asmtomsf

type ProtocolToMsfPath struct {
	Protocols []string
	MsfPaths  []string
}

var SupportProtocols = []ProtocolToMsfPath{
	{
		Protocols: []string{"http", "https"},
		MsfPaths: []string{"freebsd/http",
			"linux/http",
			"multi/http",
			"osx/http",
			"unix/http",
			"windows/http",
		},
	},
	{
		Protocols: []string{"ftp"},
		MsfPaths: []string{"freebsd/ftp",
			"linux/ftp",
			"mainframe/ftp",
			"multi/ftp",
			"osx/ftp",
			"unix/ftp",
			"windows/ftp",
		},
	},
	{
		Protocols: []string{"rdp"},
		MsfPaths:  []string{"windows/rdp"},
	},
	{
		Protocols: []string{"msrpc"},
		MsfPaths:  []string{"windows/dcerpc"},
	},
	{
		Protocols: []string{"mysql"},
		MsfPaths: []string{"linux/mysql",
			"multi/mysql",
			"windows/mysql",
		},
	},
	{
		Protocols: []string{"pptp"},
		MsfPaths:  []string{"linux/pptp"},
	},
	{
		Protocols: []string{"rtsp"},
		MsfPaths:  []string{"osx/rtsp"},
	},
	{
		Protocols: []string{"sip"},
		MsfPaths:  []string{"windows/sip"},
	},
	{
		Protocols: []string{"smtp"},
		MsfPaths: []string{
			"linux/smtp",
			"unix/smtp",
			"windows/smtp",
		},
	},

	{
		Protocols: []string{"ssh"},
		MsfPaths: []string{
			"apple_ios/ssh",
			"linux/ssh",
			"multi/ssh",
			"solaris/ssh",
			"unix/ssh",
			"windows/ssh",
		},
	},
	{
		Protocols: []string{"telnet"},
		MsfPaths: []string{
			"freebsd/telnet",
			"linux/telnet",
			"solaris/telnet",
			"windows/telnet",
		},
	},
	{
		Protocols: []string{"imap"},
		MsfPaths: []string{
			"linux/imap",
			"windows/imap",
		},
	},
	{
		Protocols: []string{"vnc"},
		MsfPaths: []string{
			"multi/vnc",
			"windows/vnc",
		},
	},
	{
		Protocols: []string{"upnp"},
		MsfPaths: []string{
			"linux/upnp",
			"multi/upnp",
		},
	},
	{
		Protocols: []string{"postgres"},
		MsfPaths: []string{
			"linux/postgres",
			"multi/postgres",
			"windows/postgres",
		},
	},
	{
		Protocols: []string{"afp"},
		MsfPaths: []string{
			"osx/afp",
		},
	},
	{
		Protocols: []string{"x11"},
		MsfPaths: []string{
			"unix/x11",
		},
	},
	{
		Protocols: []string{"mssql"},
		MsfPaths: []string{
			"unix/mssql",
		},
	},
}

var OtherMsfPathes = []string{
	"windows/antivirus",
	"windows/arkeia",
	"windows/backdoor",
	"windows/backupexec",
	"windows/brightstor",
	"windows/browser",
	"windows/email",
	"windows/emc",
	"windows/fileformat",
	"windows/firewall",
	"windows/games",
	"windows/ibm",
	"windows/iis",
	"windows/isapi",
	"windows/ldap",
	"windows/license",
	"windows/local",
	"windows/lotus",
	"windows/lpd",
	"windows/misc",
	"windows/mmsp",
	"windows/motorola",
	"windows/nfs",
	"windows/nimsoft",
	"windows/novell",
	"windows/nuuo",
	"windows/oracle",
	"windows/proxy",
	"windows/sage",
	"windows/scada",
	"windows/smb",
	"windows/ssl",
	"windows/tftp",
	"windows/unicenter",
	"windows/vpn",
	"windows/winrm",
	"unix/dhcp",
	"unix/fileformat",
	"unix/irc",
	"unix/local",
	"unix/misc",
	"unix/sonicwall",
	"unix/webapp",
	"solaris/dtspcd",
	"solaris/local",
	"solaris/lpd",
	"solaris/samba",
	"solaris/sunrpc",
	"qnx/local",
	"qnx/qconn",
	"osx/arkeia",
	"osx/browser",
	"osx/email",
	"osx/local",
	"osx/mdns",
	"osx/misc",
	"osx/samba",
	"openbsd/local",
	"netware/smb",
	"netware/sunrpc",
	"multi/browser",
	"multi/elasticsearch",
	"multi/fileformat",
	"multi/gdb",
	"multi/hams",
	"multi/ids",
	"multi/kubernetes",
	"multi/local",
	"multi/misc",
	"multi/ntp",
	"multi/php",
	"multi/realserver",
	"multi/samba",
	"multi/sap",
	"multi/scada",
	"multi/script",
	"multi/svn",
	"multi/vpn",
	"multi/wyse",
	"linux/antivirus",
	"linux/browser",
	"linux/fileformat",
	"linux/games",
	"linux/ids",
	"linux/local",
	"linux/misc",
	"linux/proxy",
	"linux/redis",
	"linux/samba",
	"linux/snmp",
	"irix/lpd",
	"hpux/lpd",
	"freebsd/local",
	"freebsd/misc",
	"freebsd/samba",
	"freebsd/tacacs",
	"freebsd/webapp",
	"firefox/local",
	"dialup/multi",
	"bsdi/softcart",
	"bsd/finger",
	"apple_ios/email",
	"apple_ios/browser",
	"android/local",
	"android/fileformat",
	"android/browser",
	"android/adb",
	"aix/local",
}
